// mobile-app/app/login.tsx
import { useState, useEffect, useMemo } from 'react';
import { View, Text, TextInput, Pressable, Image, StyleSheet, ActivityIndicator, KeyboardAvoidingView, Platform, ScrollView } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import { useAuth } from '@/store/auth';
import { http, MOCK_MODE } from '@/api/client';

/**
 * 登录 / 注册页
 * 行内校验 · 密码可见切换 · 注册时密码强度与隐私协议勾选 · 记住账号 · 验证码点击刷新 · 服务端错误行内展示
 */
const REMEMBER_KEY = 'remember_username';
const USERNAME_RE = /^[A-Za-z0-9_.@-]{2,64}$/;
const STRENGTH_LABEL = ['', '弱', '一般', '较强', '强'];
const STRENGTH_COLOR = ['#e5e7eb', '#ef4444', '#f59e0b', '#0ea5e9', '#22c55e'];

export default function LoginScreen() {
  const { login, register, loading } = useAuth();
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPwd, setShowPwd] = useState(false);
  const [remember, setRemember] = useState(true);
  const [agreed, setAgreed] = useState(false);
  const [captchaId, setCaptchaId] = useState('');
  const [captchaCode, setCaptchaCode] = useState('');
  const [captchaImg, setCaptchaImg] = useState('');
  const [captchaLoading, setCaptchaLoading] = useState(false);
  const [captchaFailed, setCaptchaFailed] = useState(false);
  const [serverError, setServerError] = useState('');
  const [touched, setTouched] = useState<Record<string, boolean>>({});

  async function loadCaptcha() {
    if (MOCK_MODE) { setCaptchaId(''); setCaptchaImg(''); return; }
    setCaptchaLoading(true);
    setCaptchaFailed(false);
    try {
      const resp = await http.get('/api/v1/auth/captcha');
      setCaptchaId(resp.data.data.captchaId);
      setCaptchaImg(resp.data.data.imageBase64);
    } catch {
      setCaptchaId('');
      setCaptchaImg('');
      setCaptchaFailed(true);
    } finally {
      setCaptchaLoading(false);
      setCaptchaCode('');
    }
  }

  useEffect(() => {
    loadCaptcha();
    SecureStore.getItemAsync(REMEMBER_KEY).then((v) => { if (v) setUsername(v); }).catch(() => {});
  }, []);

  useEffect(() => {
    setServerError('');
    setTouched({});
    setConfirmPassword('');
  }, [mode]);

  const usernameError = useMemo(() => {
    if (!touched.username) return '';
    if (!username.trim()) return '请输入账号';
    if (mode === 'register' && !USERNAME_RE.test(username.trim())) return '只能包含字母、数字、_ . @ -，2-64 位';
    return '';
  }, [touched, username, mode]);
  const passwordError = useMemo(() => {
    if (!touched.password) return '';
    if (!password) return '请输入密码';
    if (mode === 'register') {
      if (password.length < 6 || password.length > 32) return '密码长度 6-32 位';
      if (!/[A-Za-z]/.test(password) || !/[0-9]/.test(password)) return '需同时包含字母和数字';
      if (password.toLowerCase() === username.trim().toLowerCase()) return '密码不能与账号相同';
    }
    return '';
  }, [touched, password, username, mode]);
  const confirmError = useMemo(() => {
    if (mode !== 'register' || !touched.confirm) return '';
    if (!confirmPassword) return '请再次输入密码';
    if (confirmPassword !== password) return '两次输入的密码不一致';
    return '';
  }, [touched, confirmPassword, password, mode]);
  const captchaError = touched.captcha && captchaImg && !captchaCode.trim() ? '请输入验证码' : '';

  const strength = useMemo(() => {
    if (!password) return 0;
    let s = 0;
    if (password.length >= 8) s++;
    if (password.length >= 12) s++;
    if (/[A-Za-z]/.test(password) && /[0-9]/.test(password)) s++;
    if (/[^A-Za-z0-9]/.test(password)) s++;
    return Math.min(4, s);
  }, [password]);

  const canSubmit = !loading && !!username.trim() && !!password
    && (!captchaImg || !!captchaCode.trim())
    && (mode === 'login' || (!!confirmPassword && confirmPassword === password && agreed));

  const onSubmit = async () => {
    setTouched({ username: true, password: true, confirm: true, captcha: true });
    setServerError('');
    if (usernameError || passwordError || confirmError || captchaError) return;
    if (mode === 'register' && !agreed) { setServerError('请先阅读并同意《隐私政策》'); return; }
    const u = username.trim();
    try {
      if (mode === 'register') await register(u, password, confirmPassword, captchaId, captchaCode);
      else await login(u, password, captchaId, captchaCode);
      if (remember) await SecureStore.setItemAsync(REMEMBER_KEY, u);
      else await SecureStore.deleteItemAsync(REMEMBER_KEY);
    } catch (e) {
      setServerError(e instanceof Error ? e.message : (mode === 'register' ? '注册失败' : '登录失败'));
      loadCaptcha();
    }
  };

  return (
    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
        <Image source={require('../assets/icon.png')} style={styles.logo} />
        <Text style={styles.title}>知源</Text>
        <Text style={styles.subtitle}>看得懂的论文 AI 率检测 · 溯源 · 不代写</Text>

        <View style={styles.seg}>
          <Pressable style={[styles.segBtn, mode === 'login' && styles.segActive]} onPress={() => setMode('login')}>
            <Text style={mode === 'login' ? styles.segTextActive : styles.segText}>登录</Text>
          </Pressable>
          <Pressable style={[styles.segBtn, mode === 'register' && styles.segActive]} onPress={() => setMode('register')}>
            <Text style={mode === 'register' ? styles.segTextActive : styles.segText}>注册</Text>
          </Pressable>
        </View>

        <TextInput
          style={[styles.input, !!usernameError && styles.inputError]}
          placeholder="学号 / 工号 / 邮箱"
          autoCapitalize="none"
          autoCorrect={false}
          value={username}
          onChangeText={setUsername}
          onBlur={() => setTouched((t) => ({ ...t, username: true }))}
        />
        {!!usernameError && <Text style={styles.err}>{usernameError}</Text>}

        <View style={[styles.pwdRow, !!passwordError && styles.inputError]}>
          <TextInput
            style={styles.pwdInput}
            placeholder={mode === 'register' ? '设置密码（6-32 位，含字母和数字）' : '密码'}
            secureTextEntry={!showPwd}
            value={password}
            onChangeText={setPassword}
            onBlur={() => setTouched((t) => ({ ...t, password: true }))}
          />
          <Pressable onPress={() => setShowPwd((v) => !v)}><Text style={styles.eye}>{showPwd ? '隐藏' : '显示'}</Text></Pressable>
        </View>
        {!!passwordError && <Text style={styles.err}>{passwordError}</Text>}
        {mode === 'register' && !!password && (
          <View style={styles.strength}>
            {[1, 2, 3, 4].map((n) => <View key={n} style={[styles.bar, n <= strength && { backgroundColor: STRENGTH_COLOR[strength] }]} />)}
            <Text style={styles.strengthText}>{STRENGTH_LABEL[strength]}</Text>
          </View>
        )}

        {mode === 'register' && (
          <>
            <TextInput
              style={[styles.input, !!confirmError && styles.inputError]}
              placeholder="再次输入密码"
              secureTextEntry={!showPwd}
              value={confirmPassword}
              onChangeText={setConfirmPassword}
              onBlur={() => setTouched((t) => ({ ...t, confirm: true }))}
            />
            {!!confirmError && <Text style={styles.err}>{confirmError}</Text>}
          </>
        )}

        {!MOCK_MODE && (
          <View style={styles.captchaRow}>
            <TextInput
              style={[styles.input, styles.captchaInput, !!captchaError && styles.inputError]}
              placeholder="验证码"
              autoCapitalize="characters"
              maxLength={6}
              value={captchaCode}
              onChangeText={setCaptchaCode}
              onBlur={() => setTouched((t) => ({ ...t, captcha: true }))}
            />
            <Pressable style={styles.captchaBox} onPress={loadCaptcha} disabled={captchaLoading}>
              {captchaImg && !captchaLoading
                ? <Image source={{ uri: captchaImg }} style={styles.captchaImg} />
                : <Text style={styles.captchaHint}>{captchaLoading ? '加载中…' : captchaFailed ? '点击重试' : '获取验证码'}</Text>}
            </Pressable>
          </View>
        )}
        {!!captchaError && <Text style={styles.err}>{captchaError}</Text>}
        {!captchaError && captchaFailed && <Text style={styles.err}>验证码服务暂时不可用，点击右侧重试</Text>}

        <View style={styles.opts}>
          <Pressable style={styles.chk} onPress={() => setRemember((v) => !v)}>
            <View style={[styles.box, remember && styles.boxOn]}>{remember && <Text style={styles.tick}>✓</Text>}</View>
            <Text style={styles.chkText}>记住账号</Text>
          </Pressable>
          {mode === 'register' ? (
            <Pressable style={styles.chk} onPress={() => setAgreed((v) => !v)}>
              <View style={[styles.box, agreed && styles.boxOn]}>{agreed && <Text style={styles.tick}>✓</Text>}</View>
              <Text style={styles.chkText}>同意<Text style={styles.link}>《隐私政策》</Text></Text>
            </Pressable>
          ) : <Text style={styles.muted}>忘记密码请联系管理员</Text>}
        </View>

        {!!serverError && <View style={styles.serverError}><Text style={styles.serverErrorText}>{serverError}</Text></View>}

        <Pressable style={[styles.button, !canSubmit && styles.buttonDisabled]} onPress={onSubmit} disabled={!canSubmit}>
          {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>{mode === 'login' ? '登 录' : '注册并登录'}</Text>}
        </Pressable>

        <Text style={styles.hint} onPress={() => setMode(mode === 'login' ? 'register' : 'login')}>
          {mode === 'login' ? '还没有账号？立即注册' : '已有账号？去登录'}
        </Text>
        <Text style={styles.foot}>课题阶段免费 · 不代写、不改写 · 结果仅供参考</Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 32, paddingVertical: 48, backgroundColor: '#fff' },
  logo: { width: 56, height: 56, borderRadius: 14, alignSelf: 'center', marginBottom: 12 },
  title: { fontSize: 28, fontWeight: '700', textAlign: 'center', color: '#0D9488' },
  subtitle: { fontSize: 13, textAlign: 'center', color: '#6b7280', marginTop: 8, marginBottom: 28 },
  seg: { flexDirection: 'row', backgroundColor: '#f3f4f6', borderRadius: 10, padding: 3, marginBottom: 18 },
  segBtn: { flex: 1, alignItems: 'center', paddingVertical: 8, borderRadius: 8 },
  segActive: { backgroundColor: '#fff', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 3, elevation: 1 },
  segText: { color: '#6b7280', fontSize: 15 },
  segTextActive: { color: '#111827', fontSize: 15, fontWeight: '600' },
  input: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, marginBottom: 12 },
  inputError: { borderColor: '#ef4444' },
  pwdRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#d1d5db', borderRadius: 10, paddingRight: 12, marginBottom: 12 },
  pwdInput: { flex: 1, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16 },
  eye: { color: '#0D9488', fontSize: 13 },
  err: { color: '#ef4444', fontSize: 12, marginTop: -6, marginBottom: 10, marginLeft: 4 },
  strength: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: -4, marginBottom: 10 },
  bar: { width: 36, height: 4, borderRadius: 2, backgroundColor: '#e5e7eb' },
  strengthText: { fontSize: 12, color: '#6b7280', marginLeft: 6 },
  captchaRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  captchaInput: { flex: 1 },
  captchaBox: { width: 108, height: 46, borderRadius: 10, borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  captchaImg: { width: '100%', height: '100%' },
  captchaHint: { fontSize: 12, color: '#0D9488' },
  opts: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 2, flexWrap: 'wrap', gap: 8 },
  chk: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  box: { width: 18, height: 18, borderRadius: 4, borderWidth: 1.5, borderColor: '#9ca3af', alignItems: 'center', justifyContent: 'center' },
  boxOn: { backgroundColor: '#0D9488', borderColor: '#0D9488' },
  tick: { color: '#fff', fontSize: 12, lineHeight: 14 },
  chkText: { fontSize: 13, color: '#6b7280' },
  link: { color: '#0D9488' },
  muted: { fontSize: 12, color: '#9ca3af' },
  serverError: { marginTop: 12, padding: 10, borderRadius: 10, backgroundColor: 'rgba(239,68,68,0.08)' },
  serverErrorText: { color: '#b91c1c', fontSize: 13, lineHeight: 18 },
  button: { backgroundColor: '#0D9488', borderRadius: 10, paddingVertical: 14, alignItems: 'center', marginTop: 16 },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  hint: { fontSize: 13, color: '#0D9488', textAlign: 'center', marginTop: 20 },
  foot: { fontSize: 11, color: '#9ca3af', textAlign: 'center', marginTop: 10 },
});

// web/src/views/Login.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch, nextTick } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useAuthStore } from '@/stores/auth'
import { getCaptcha } from '@/api/auth'

/**
 * 登录 / 注册页
 *   左栏（≥ 900px）：品牌 + 三条价值主张；右栏：表单
 *   表单：行内校验 · 密码可见切换 · 注册时密码强度与协议勾选 · 记住账号 · 验证码点击刷新
 *   服务端错误（锁定 / 验证码 / 账号停用）显示在表单内，不只靠 toast
 */

const auth = useAuthStore()
const router = useRouter()
const route = useRoute()

const REMEMBER_KEY = 'remember_username'
const mode = ref<'login' | 'register'>(route.query.mode === 'register' ? 'register' : 'login')
const username = ref('')
const password = ref('')
const confirmPassword = ref('')
const showPwd = ref(false)
const remember = ref(true)
const agreed = ref(false)
const captchaId = ref('')
const captchaCode = ref('')
const captchaImg = ref('')
const captchaLoading = ref(false)
const captchaFailed = ref(false)
const serverError = ref('')
const touched = ref<Record<string, boolean>>({})
const usernameInput = ref<HTMLInputElement | null>(null)
const captchaInput = ref<HTMLInputElement | null>(null)

const VALUE_PROPS = [
  { t: '不只给 AI 率', d: '逐段解释为什么像 AI，哪一句最可疑' },
  { t: '溯源哪家大模型', d: '疑似 GPT / 通义 / DeepSeek，知道像谁才知道怎么不像' },
  { t: '原创被误判有路可走', d: '一键生成申诉材料，不推销「降 AI」' },
]

/* ---------- 行内校验 ---------- */
const USERNAME_RE = /^[A-Za-z0-9_.@-]{2,64}$/
const usernameError = computed(() => {
  if (!touched.value.username) return ''
  if (!username.value.trim()) return '请输入账号'
  if (mode.value === 'register' && !USERNAME_RE.test(username.value.trim())) return '只能包含字母、数字、_ . @ -，2-64 位'
  return ''
})
const passwordError = computed(() => {
  if (!touched.value.password) return ''
  if (!password.value) return '请输入密码'
  if (mode.value === 'register') {
    if (password.value.length < 6 || password.value.length > 32) return '密码长度 6-32 位'
    if (!/[A-Za-z]/.test(password.value) || !/[0-9]/.test(password.value)) return '需同时包含字母和数字'
    if (password.value.toLowerCase() === username.value.trim().toLowerCase()) return '密码不能与账号相同'
  }
  return ''
})
const confirmError = computed(() => {
  if (mode.value !== 'register' || !touched.value.confirm) return ''
  if (!confirmPassword.value) return '请再次输入密码'
  if (confirmPassword.value !== password.value) return '两次输入的密码不一致'
  return ''
})
const captchaError = computed(() => (touched.value.captcha && captchaImg.value && !captchaCode.value.trim() ? '请输入验证码' : ''))

/* 密码强度：长度 + 字符种类 */
const strength = computed(() => {
  const p = password.value
  if (!p) return 0
  let s = 0
  if (p.length >= 8) s++
  if (p.length >= 12) s++
  if (/[A-Za-z]/.test(p) && /[0-9]/.test(p)) s++
  if (/[^A-Za-z0-9]/.test(p)) s++
  return Math.min(4, s)
})
const STRENGTH_LABEL = ['', '弱', '一般', '较强', '强']

const canSubmit = computed(() => {
  if (auth.loading) return false
  if (!username.value.trim() || !password.value) return false
  if (captchaImg.value && !captchaCode.value.trim()) return false
  if (mode.value === 'register') {
    if (!confirmPassword.value || confirmPassword.value !== password.value) return false
    if (!agreed.value) return false
  }
  return true
})

/* ---------- 验证码 ---------- */
async function loadCaptcha() {
  captchaLoading.value = true
  captchaFailed.value = false
  try {
    const c = await getCaptcha()
    captchaId.value = c.captchaId
    captchaImg.value = c.imageBase64
  } catch {
    captchaId.value = ''
    captchaImg.value = ''
    captchaFailed.value = true
  } finally {
    captchaLoading.value = false
    captchaCode.value = ''
  }
}

onMounted(() => {
  try {
    const saved = localStorage.getItem(REMEMBER_KEY)
    if (saved) { username.value = saved; remember.value = true }
  } catch { /* ignore */ }
  loadCaptcha()
  nextTick(() => (username.value ? captchaInput.value : usernameInput.value)?.focus())
})

watch(mode, () => {
  serverError.value = ''
  touched.value = {}
  confirmPassword.value = ''
  if (!captchaImg.value) loadCaptcha()
})

function touchAll() {
  touched.value = { username: true, password: true, confirm: true, captcha: true }
}

async function onSubmit() {
  touchAll()
  serverError.value = ''
  if (usernameError.value || passwordError.value || confirmError.value || captchaError.value) return
  if (mode.value === 'register' && !agreed.value) {
    serverError.value = '请先阅读并同意《隐私政策》'
    return
  }
  const u = username.value.trim()
  try {
    if (mode.value === 'register') {
      await auth.register(u, password.value, confirmPassword.value, captchaId.value, captchaCode.value)
      ElMessage.success('注册成功，已自动登录')
    } else {
      await auth.login(u, password.value, captchaId.value, captchaCode.value)
    }
    try {
      if (remember.value) localStorage.setItem(REMEMBER_KEY, u)
      else localStorage.removeItem(REMEMBER_KEY)
    } catch { /* ignore */ }
    const redirect = (route.query.redirect as string) || '/dashboard'
    router.replace(redirect.startsWith('/') ? redirect : '/dashboard')
  } catch (e: any) {
    serverError.value = e?.message || (mode.value === 'register' ? '注册失败' : '登录失败')
    // 验证码一次性：失败后必须换一张
    loadCaptcha()
    nextTick(() => captchaInput.value?.focus())
  }
}
</script>

<template>
  <div class="login-page">
    <aside class="side">
      <router-link to="/" class="side-brand"><img src="/logo.png" alt="" class="side-logo" />知源</router-link>
      <h1 class="side-title">看得懂的<br />论文 AI 率检测</h1>
      <ul class="side-props">
        <li v-for="p in VALUE_PROPS" :key="p.t"><b>{{ p.t }}</b><span>{{ p.d }}</span></li>
      </ul>
      <div class="side-foot">课题阶段免费 · 不代写、不改写 · 结果仅供参考</div>
    </aside>

    <main class="panel">
      <div class="wrap">
        <div class="hero">
          <div class="brand">{{ mode === 'login' ? '欢迎回来' : '创建账号' }}</div>
          <div class="tagline">{{ mode === 'login' ? '登录后查看报告、问小白、提交申诉' : '一分钟注册，课题阶段免费使用' }}</div>
        </div>

        <div class="seg" role="tablist">
          <button class="seg-btn" :class="{ active: mode === 'login' }" role="tab" @click="mode = 'login'">登录</button>
          <button class="seg-btn" :class="{ active: mode === 'register' }" role="tab" @click="mode = 'register'">注册</button>
        </div>

        <form class="form" novalidate @submit.prevent="onSubmit">
          <div class="field" :class="{ error: usernameError }">
            <input ref="usernameInput" v-model="username" placeholder="学号 / 工号 / 邮箱" class="apple-input" autocomplete="username" @blur="touched.username = true" />
          </div>
          <div v-if="usernameError" class="err">{{ usernameError }}</div>

          <div class="field pwd" :class="{ error: passwordError }">
            <input v-model="password" :type="showPwd ? 'text' : 'password'" :placeholder="mode === 'register' ? '设置密码（6-32 位，含字母和数字）' : '密码'" class="apple-input" :autocomplete="mode === 'register' ? 'new-password' : 'current-password'" @blur="touched.password = true" />
            <button type="button" class="eye" :aria-label="showPwd ? '隐藏密码' : '显示密码'" @click="showPwd = !showPwd">{{ showPwd ? '隐藏' : '显示' }}</button>
          </div>
          <div v-if="passwordError" class="err">{{ passwordError }}</div>
          <div v-if="mode === 'register' && password" class="strength">
            <i v-for="n in 4" :key="n" :class="{ on: n <= strength, ['lv' + strength]: n <= strength }" />
            <span>{{ STRENGTH_LABEL[strength] }}</span>
          </div>

          <template v-if="mode === 'register'">
            <div class="field" :class="{ error: confirmError }">
              <input v-model="confirmPassword" :type="showPwd ? 'text' : 'password'" placeholder="再次输入密码" class="apple-input" autocomplete="new-password" @blur="touched.confirm = true" />
            </div>
            <div v-if="confirmError" class="err">{{ confirmError }}</div>
          </template>

          <div class="captcha-row">
            <div class="field captcha-field" :class="{ error: captchaError }">
              <input ref="captchaInput" v-model="captchaCode" placeholder="验证码" class="apple-input" maxlength="6" autocomplete="off" @blur="touched.captcha = true" />
            </div>
            <button type="button" class="captcha-box" :disabled="captchaLoading" title="看不清？点击换一张" @click="loadCaptcha">
              <img v-if="captchaImg && !captchaLoading" :src="captchaImg" alt="验证码" />
              <span v-else-if="captchaLoading" class="captcha-hint">加载中…</span>
              <span v-else class="captcha-hint">{{ captchaFailed ? '点击重试' : '获取验证码' }}</span>
            </button>
          </div>
          <div v-if="captchaError" class="err">{{ captchaError }}</div>
          <div v-else-if="captchaFailed" class="err">验证码服务暂时不可用，点击右侧重试</div>

          <div class="opts">
            <label class="chk"><input v-model="remember" type="checkbox" /> 记住账号</label>
            <label v-if="mode === 'register'" class="chk"><input v-model="agreed" type="checkbox" /> 我已阅读并同意 <router-link to="/privacy" target="_blank" class="link">《隐私政策》</router-link></label>
            <span v-else class="muted">忘记密码？请联系学校管理员重置</span>
          </div>

          <div v-if="serverError" class="server-error" role="alert">{{ serverError }}</div>

          <el-button
            type="primary" round size="large" native-type="submit"
            :loading="auth.loading" :disabled="!canSubmit"
            style="width: 100%; margin-top: 12px; height: 50px; font-size: 17px"
          >{{ mode === 'login' ? '登 录' : '注册并登录' }}</el-button>

          <div class="footer-hint">
            {{ mode === 'login' ? '还没有账号？' : '已有账号？' }}
            <span class="switch-link" @click="mode = mode === 'login' ? 'register' : 'login'">{{ mode === 'login' ? '立即注册' : '去登录' }}</span>
          </div>
        </form>
      </div>
    </main>
  </div>
</template>

<style scoped>
.login-page { min-height: 100vh; display: grid; grid-template-columns: minmax(0, 5fr) minmax(0, 6fr); background: var(--system-background); }
.side { background: linear-gradient(160deg, #0B1F3A 0%, #10355E 55%, #0D9488 130%); color: #fff; padding: 48px 56px; display: flex; flex-direction: column; }
.side-brand { display: inline-flex; align-items: center; gap: 10px; color: #fff; text-decoration: none; font-weight: 700; font-size: 18px; letter-spacing: -0.3px; }
.side-logo { width: 28px; height: 28px; border-radius: 8px; object-fit: cover; }
.side-title { font-size: 38px; line-height: 1.2; letter-spacing: -1px; margin: 72px 0 36px; font-weight: 700; }
.side-props { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 22px; }
.side-props li { display: flex; flex-direction: column; gap: 4px; padding-left: 16px; border-left: 2px solid rgba(255, 255, 255, 0.35); }
.side-props b { font-size: 16px; } .side-props span { font-size: 14px; color: rgba(255, 255, 255, 0.72); line-height: 1.5; }
.side-foot { margin-top: auto; font-size: 12px; color: rgba(255, 255, 255, 0.55); }

.panel { display: flex; align-items: center; justify-content: center; padding: 48px 24px; }
.wrap { width: 100%; max-width: 380px; }
.hero { margin-bottom: 32px; }
.brand { font-size: var(--fs-large-title); font-weight: var(--fw-bold); letter-spacing: -0.8px; color: var(--label); line-height: 1.1; }
.tagline { font-size: var(--fs-subhead); color: var(--label-secondary); margin-top: 8px; }

.seg { display: flex; background: rgba(120, 120, 128, 0.12); border-radius: var(--radius-btn); padding: 3px; margin-bottom: 16px; }
.seg-btn { flex: 1; border: none; background: transparent; color: var(--label); font-size: var(--fs-subhead); font-weight: var(--fw-medium); padding: 8px 0; border-radius: 8px; cursor: pointer; font-family: inherit; transition: background-color var(--dur-fast); }
.seg-btn.active { background: #fff; font-weight: var(--fw-semibold); box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05); }

.field { background: rgba(120, 120, 128, 0.12); border-radius: var(--radius-btn); padding: 2px 16px; margin-bottom: 10px; border: 1px solid transparent; transition: border-color var(--dur-fast); }
.field:focus-within { border-color: var(--system-blue); background: #fff; }
.field.error { border-color: var(--system-red); }
.field.pwd { display: flex; align-items: center; gap: 8px; }
.eye { border: none; background: transparent; color: var(--system-blue); font-size: 13px; cursor: pointer; font-family: inherit; padding: 4px 0 4px 8px; flex: none; }
.err { margin: -6px 0 10px 6px; font-size: 12px; color: var(--system-red); }
.apple-input { width: 100%; height: 46px; border: none; background: transparent; outline: none; font-size: var(--fs-body); color: var(--label); font-family: inherit; min-width: 0; }
.apple-input::placeholder { color: var(--label-tertiary); }

.strength { display: flex; align-items: center; gap: 4px; margin: -4px 0 10px 4px; }
.strength i { width: 36px; height: 4px; border-radius: 2px; background: rgba(120, 120, 128, 0.2); }
.strength i.on.lv1 { background: var(--system-red); } .strength i.on.lv2 { background: var(--system-orange); } .strength i.on.lv3 { background: var(--system-teal); } .strength i.on.lv4 { background: var(--system-green); }
.strength span { font-size: 12px; color: var(--label-secondary); margin-left: 6px; }

.captcha-row { display: flex; gap: 10px; align-items: flex-start; }
.captcha-field { flex: 1; }
.captcha-box { flex: none; width: 112px; height: 50px; border: 1px solid var(--label-quaternary); border-radius: var(--radius-btn); background: #fff; padding: 0; overflow: hidden; cursor: pointer; display: flex; align-items: center; justify-content: center; }
.captcha-box img { width: 100%; height: 100%; object-fit: cover; display: block; }
.captcha-hint { font-size: 12px; color: var(--system-blue); }

.opts { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin: 4px 2px 0; font-size: 13px; flex-wrap: wrap; }
.chk { display: inline-flex; align-items: center; gap: 6px; color: var(--label-secondary); cursor: pointer; }
.chk input { accent-color: var(--system-blue); }
.link { color: var(--system-blue); text-decoration: none; }
.muted { color: var(--label-tertiary); font-size: 12px; }

.server-error { margin-top: 12px; padding: 10px 12px; border-radius: 10px; background: rgba(255, 59, 48, 0.08); color: #C62A22; font-size: 13px; line-height: 1.5; }

.footer-hint { margin-top: 24px; font-size: var(--fs-caption-1); color: var(--label-secondary); text-align: center; }
.switch-link { color: var(--system-blue); cursor: pointer; margin-left: 4px; }

@media (max-width: 900px) {
  .login-page { grid-template-columns: 1fr; }
  .side { display: none; }
  .panel { align-items: flex-start; padding-top: 72px; }
}
</style>
