// mobile-app/app/(tabs)/upload.tsx
import { useState } from 'react';
import { View, Text, Pressable, StyleSheet, Alert, ActivityIndicator } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { useRouter } from 'expo-router';
import { useQueryClient } from '@tanstack/react-query';
import { uploadPaper } from '@/api/detect';

const DEGREES = [
  { key: 'BACHELOR', label: '本科', threshold: 20 },
  { key: 'MASTER', label: '硕士', threshold: 15 },
  { key: 'PHD', label: '博士', threshold: 10 },
] as const;

export default function UploadScreen() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [degree, setDegree] = useState<string>('BACHELOR');
  const [file, setFile] = useState<{ uri: string; name: string; mimeType?: string } | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const pickFile = async () => {
    const result = await DocumentPicker.getDocumentAsync({
      type: [
        'application/pdf',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'text/plain',
      ],
      copyToCacheDirectory: true,
    });
    if (!result.canceled && result.assets[0]) {
      const asset = result.assets[0];
      if (asset.size && asset.size > 20 * 1024 * 1024) {
        Alert.alert('提示', '文件不能超过 20MB');
        return;
      }
      setFile({ uri: asset.uri, name: asset.name, mimeType: asset.mimeType });
    }
  };

  const submit = async () => {
    if (!file) {
      Alert.alert('提示', '请先选择论文文件');
      return;
    }
    setSubmitting(true);
    try {
      await uploadPaper(file, degree);
      await queryClient.invalidateQueries({ queryKey: ['tasks'] });
      Alert.alert('提交成功', '检测任务已创建，请在「检测记录」查看进度', [
        { text: '查看', onPress: () => router.push('/') },
      ]);
      setFile(null);
    } catch (e) {
      Alert.alert('提交失败', e instanceof Error ? e.message : '请稍后重试');
    } finally {
      setSubmitting(false);
    }
  };

  const currentThreshold = DEGREES.find((d) => d.key === degree)?.threshold;

  return (
    <View style={styles.container}>
      <Text style={styles.sectionTitle}>学位类型</Text>
      <View style={styles.degreeRow}>
        {DEGREES.map((d) => (
          <Pressable
            key={d.key}
            style={[styles.degreeChip, degree === d.key && styles.degreeChipActive]}
            onPress={() => setDegree(d.key)}
          >
            <Text style={[styles.degreeText, degree === d.key && styles.degreeTextActive]}>
              {d.label}
            </Text>
          </Pressable>
        ))}
      </View>
      <Text style={styles.thresholdHint}>教育部红线：AI 率 ≤ {currentThreshold}%</Text>

      <Text style={styles.sectionTitle}>论文文件</Text>
      <Pressable style={styles.fileBox} onPress={pickFile}>
        <Text style={styles.fileBoxIcon}>{file ? '📄' : '📎'}</Text>
        <Text style={styles.fileBoxText} numberOfLines={1}>
          {file ? file.name : '点击选择 PDF / Word / TXT（≤ 20MB）'}
        </Text>
      </Pressable>

      <Pressable style={[styles.submitBtn, (!file || submitting) && styles.submitBtnDisabled]} onPress={submit} disabled={!file || submitting}>
        {submitting ? <ActivityIndicator color="#fff" /> : <Text style={styles.submitText}>提交检测</Text>}
      </Pressable>

      <Text style={styles.privacyHint}>
        论文原文加密存储，30 天后自动删除；检测报告保留 3 年
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff', padding: 20 },
  sectionTitle: { fontSize: 14, fontWeight: '600', color: '#374151', marginTop: 20, marginBottom: 10 },
  degreeRow: { flexDirection: 'row', gap: 10 },
  degreeChip: {
    paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20,
    borderWidth: 1, borderColor: '#d1d5db',
  },
  degreeChipActive: { backgroundColor: '#1a56db', borderColor: '#1a56db' },
  degreeText: { fontSize: 14, color: '#374151' },
  degreeTextActive: { color: '#fff', fontWeight: '600' },
  thresholdHint: { fontSize: 12, color: '#f59e0b', marginTop: 8 },
  fileBox: {
    borderWidth: 1.5, borderColor: '#d1d5db', borderStyle: 'dashed', borderRadius: 12,
    paddingVertical: 36, alignItems: 'center', backgroundColor: '#f9fafb',
  },
  fileBoxIcon: { fontSize: 32, marginBottom: 8 },
  fileBoxText: { fontSize: 13, color: '#6b7280', paddingHorizontal: 20 },
  submitBtn: {
    backgroundColor: '#1a56db', borderRadius: 10, paddingVertical: 14,
    alignItems: 'center', marginTop: 28,
  },
  submitBtnDisabled: { opacity: 0.4 },
  submitText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  privacyHint: { fontSize: 11, color: '#9ca3af', textAlign: 'center', marginTop: 16 },
});

// mobile-uniapp/pages/upload/upload.vue
<script setup>
import { ref, computed } from 'vue'
import { uploadPaper } from '@/api/detect'

const DEGREES = [
  { key: 'BACHELOR', label: '本科', threshold: 20 },
  { key: 'MASTER',   label: '硕士', threshold: 15 },
  { key: 'PHD',      label: '博士', threshold: 10 },
]

const degree = ref('BACHELOR')
const file = ref(null)          // { path, name, size }
const submitting = ref(false)

const threshold = computed(() => DEGREES.find(d => d.key === degree.value)?.threshold)

/**
 * 选文件
 *   小程序端优先用 chooseMessageFile（从聊天转发），H5 端 fallback 到 chooseFile
 */
function pickFile() {
  // #ifdef MP-WEIXIN
  uni.chooseMessageFile({
    count: 1,
    type: 'file',
    extension: ['.pdf', '.doc', '.docx', '.txt'],
    success: (res) => {
      const f = res.tempFiles[0]
      if (f.size > 20 * 1024 * 1024) {
        uni.showToast({ title: '文件不能超过 20MB', icon: 'none' })
        return
      }
      file.value = { path: f.path, name: f.name, size: f.size }
    },
  })
  // #endif

  // #ifdef H5
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = '.pdf,.doc,.docx,.txt'
  input.onchange = (e) => {
    const f = e.target.files[0]
    if (!f) return
    if (f.size > 20 * 1024 * 1024) {
      uni.showToast({ title: '文件不能超过 20MB', icon: 'none' })
      return
    }
    const url = URL.createObjectURL(f)
    file.value = { path: url, name: f.name, size: f.size }
  }
  input.click()
  // #endif
}

async function submit() {
  if (!file.value) {
    uni.showToast({ title: '请先选择论文文件', icon: 'none' })
    return
  }
  submitting.value = true
  try {
    await uploadPaper(file.value.path, file.value.name, degree.value)
    uni.showToast({ title: '提交成功', icon: 'success' })
    file.value = null
    setTimeout(() => uni.switchTab({ url: '/pages/index/index' }), 800)
  } catch (e) {
    uni.showToast({ title: e?.message || '提交失败', icon: 'none' })
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <view class="container">
    <text class="section-title">学位类型</text>
    <view class="degree-row">
      <view
        v-for="d in DEGREES" :key="d.key"
        class="chip" :class="{ active: degree === d.key }"
        @click="degree = d.key"
      >{{ d.label }}</view>
    </view>
    <text class="threshold-hint">教育部红线：AI 率 ≤ {{ threshold }}%</text>

    <text class="section-title">论文文件</text>
    <view class="file-box" @click="pickFile">
      <text class="file-icon">{{ file ? '📄' : '📎' }}</text>
      <text class="file-name">
        {{ file ? file.name : '点击选择 PDF / Word / TXT（≤ 20MB）' }}
      </text>
    </view>

    <button
      class="submit"
      :disabled="!file || submitting"
      :loading="submitting"
      @click="submit"
    >提交检测</button>

    <text class="privacy">论文原文加密存储，30 天后自动删除；检测报告保留 3 年</text>
  </view>
</template>

<style lang="scss" scoped>
.container {
  padding: 40rpx;
  background: #fff;
  min-height: 100vh;
}

.section-title {
  display: block;
  font-size: 28rpx;
  font-weight: 600;
  color: #374151;
  margin: 40rpx 0 20rpx;
}

.degree-row {
  display: flex;
  gap: 20rpx;
}
.chip {
  padding: 20rpx 40rpx;
  border-radius: 40rpx;
  border: 1rpx solid #d1d5db;
  font-size: 28rpx;
  color: #374151;
  &.active {
    background: #1a56db;
    color: #fff;
    border-color: #1a56db;
    font-weight: 600;
  }
}

.threshold-hint {
  display: block;
  margin-top: 16rpx;
  font-size: 24rpx;
  color: #f59e0b;
}

.file-box {
  border: 3rpx dashed #d1d5db;
  border-radius: 20rpx;
  padding: 72rpx 20rpx;
  text-align: center;
  background: #f9fafb;
}
.file-icon { display: block; font-size: 64rpx; margin-bottom: 16rpx; }
.file-name { display: block; font-size: 26rpx; color: #6b7280; }

.submit {
  margin-top: 56rpx;
  background: #1a56db;
  color: #fff;
  font-size: 32rpx;
  font-weight: 600;
  border-radius: 16rpx;
  &[disabled] { opacity: 0.4; }
}

.privacy {
  display: block;
  margin-top: 32rpx;
  font-size: 22rpx;
  color: #9ca3af;
  text-align: center;
}
</style>
