// mobile-app/app/login.tsx
import { useState, useEffect, useMemo } from 'react';
import { View, Text, TextInput, Pressable, Image, StyleSheet, ActivityIndicator, KeyboardAvoidingView, Platform, ScrollView } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import { useAuth } from '@/store/auth';
import { http, MOCK_MODE } from '@/api/client';

/**
 * 登录 / 注册页
 * 行内校验 · 密码可见切换 · 注册时密码强度与隐私协议勾选 · 记住账号 · 验证码点击刷新 · 服务端错误行内展示
 */
const REMEMBER_KEY = 'remember_username';
const USERNAME_RE = /^[A-Za-z0-9_.@-]{2,64}$/;
const STRENGTH_LABEL = ['', '弱', '一般', '较强', '强'];
const STRENGTH_COLOR = ['#e5e7eb', '#ef4444', '#f59e0b', '#0ea5e9', '#22c55e'];

export default function LoginScreen() {
  const { login, register, loading } = useAuth();
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPwd, setShowPwd] = useState(false);
  const [remember, setRemember] = useState(true);
  const [agreed, setAgreed] = useState(false);
  const [captchaId, setCaptchaId] = useState('');
  const [captchaCode, setCaptchaCode] = useState('');
  const [captchaImg, setCaptchaImg] = useState('');
  const [captchaLoading, setCaptchaLoading] = useState(false);
  const [captchaFailed, setCaptchaFailed] = useState(false);
  const [serverError, setServerError] = useState('');
  const [touched, setTouched] = useState<Record<string, boolean>>({});

  async function loadCaptcha() {
    if (MOCK_MODE) { setCaptchaId(''); setCaptchaImg(''); return; }
    setCaptchaLoading(true);
    setCaptchaFailed(false);
    try {
      const resp = await http.get('/api/v1/auth/captcha');
      setCaptchaId(resp.data.data.captchaId);
      setCaptchaImg(resp.data.data.imageBase64);
    } catch {
      setCaptchaId('');
      setCaptchaImg('');
      setCaptchaFailed(true);
    } finally {
      setCaptchaLoading(false);
      setCaptchaCode('');
    }
  }

  useEffect(() => {
    loadCaptcha();
    SecureStore.getItemAsync(REMEMBER_KEY).then((v) => { if (v) setUsername(v); }).catch(() => {});
  }, []);

  useEffect(() => {
    setServerError('');
    setTouched({});
    setConfirmPassword('');
  }, [mode]);

  const usernameError = useMemo(() => {
    if (!touched.username) return '';
    if (!username.trim()) return '请输入账号';
    if (mode === 'register' && !USERNAME_RE.test(username.trim())) return '只能包含字母、数字、_ . @ -，2-64 位';
    return '';
  }, [touched, username, mode]);
  const passwordError = useMemo(() => {
    if (!touched.password) return '';
    if (!password) return '请输入密码';
    if (mode === 'register') {
      if (password.length < 6 || password.length > 32) return '密码长度 6-32 位';
      if (!/[A-Za-z]/.test(password) || !/[0-9]/.test(password)) return '需同时包含字母和数字';
      if (password.toLowerCase() === username.trim().toLowerCase()) return '密码不能与账号相同';
    }
    return '';
  }, [touched, password, username, mode]);
  const confirmError = useMemo(() => {
    if (mode !== 'register' || !touched.confirm) return '';
    if (!confirmPassword) return '请再次输入密码';
    if (confirmPassword !== password) return '两次输入的密码不一致';
    return '';
  }, [touched, confirmPassword, password, mode]);
  const captchaError = touched.captcha && captchaImg && !captchaCode.trim() ? '请输入验证码' : '';

  const strength = useMemo(() => {
    if (!password) return 0;
    let s = 0;
    if (password.length >= 8) s++;
    if (password.length >= 12) s++;
    if (/[A-Za-z]/.test(password) && /[0-9]/.test(password)) s++;
    if (/[^A-Za-z0-9]/.test(password)) s++;
    return Math.min(4, s);
  }, [password]);

  const canSubmit = !loading && !!username.trim() && !!password
    && (!captchaImg || !!captchaCode.trim())
    && (mode === 'login' || (!!confirmPassword && confirmPassword === password && agreed));

  const onSubmit = async () => {
    setTouched({ username: true, password: true, confirm: true, captcha: true });
    setServerError('');
    if (usernameError || passwordError || confirmError || captchaError) return;
    if (mode === 'register' && !agreed) { setServerError('请先阅读并同意《隐私政策》'); return; }
    const u = username.trim();
    try {
      if (mode === 'register') await register(u, password, confirmPassword, captchaId, captchaCode);
      else await login(u, password, captchaId, captchaCode);
      if (remember) await SecureStore.setItemAsync(REMEMBER_KEY, u);
      else await SecureStore.deleteItemAsync(REMEMBER_KEY);
    } catch (e) {
      setServerError(e instanceof Error ? e.message : (mode === 'register' ? '注册失败' : '登录失败'));
      loadCaptcha();
    }
  };

  return (
    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
        <Image source={require('../assets/icon.png')} style={styles.logo} />
        <Text style={styles.title}>知源</Text>
        <Text style={styles.subtitle}>看得懂的论文 AI 率检测 · 溯源 · 不代写</Text>

        <View style={styles.seg}>
          <Pressable style={[styles.segBtn, mode === 'login' && styles.segActive]} onPress={() => setMode('login')}>
            <Text style={mode === 'login' ? styles.segTextActive : styles.segText}>登录</Text>
          </Pressable>
          <Pressable style={[styles.segBtn, mode === 'register' && styles.segActive]} onPress={() => setMode('register')}>
            <Text style={mode === 'register' ? styles.segTextActive : styles.segText}>注册</Text>
          </Pressable>
        </View>

        <TextInput
          style={[styles.input, !!usernameError && styles.inputError]}
          placeholder="学号 / 工号 / 邮箱"
          autoCapitalize="none"
          autoCorrect={false}
          value={username}
          onChangeText={setUsername}
          onBlur={() => setTouched((t) => ({ ...t, username: true }))}
        />
        {!!usernameError && <Text style={styles.err}>{usernameError}</Text>}

        <View style={[styles.pwdRow, !!passwordError && styles.inputError]}>
          <TextInput
            style={styles.pwdInput}
            placeholder={mode === 'register' ? '设置密码（6-32 位，含字母和数字）' : '密码'}
            secureTextEntry={!showPwd}
            value={password}
            onChangeText={setPassword}
            onBlur={() => setTouched((t) => ({ ...t, password: true }))}
          />
          <Pressable onPress={() => setShowPwd((v) => !v)}><Text style={styles.eye}>{showPwd ? '隐藏' : '显示'}</Text></Pressable>
        </View>
        {!!passwordError && <Text style={styles.err}>{passwordError}</Text>}
        {mode === 'register' && !!password && (
          <View style={styles.strength}>
            {[1, 2, 3, 4].map((n) => <View key={n} style={[styles.bar, n <= strength && { backgroundColor: STRENGTH_COLOR[strength] }]} />)}
            <Text style={styles.strengthText}>{STRENGTH_LABEL[strength]}</Text>
          </View>
        )}

        {mode === 'register' && (
          <>
            <TextInput
              style={[styles.input, !!confirmError && styles.inputError]}
              placeholder="再次输入密码"
              secureTextEntry={!showPwd}
              value={confirmPassword}
              onChangeText={setConfirmPassword}
              onBlur={() => setTouched((t) => ({ ...t, confirm: true }))}
            />
            {!!confirmError && <Text style={styles.err}>{confirmError}</Text>}
          </>
        )}

        {!MOCK_MODE && (
          <View style={styles.captchaRow}>
            <TextInput
              style={[styles.input, styles.captchaInput, !!captchaError && styles.inputError]}
              placeholder="验证码"
              autoCapitalize="characters"
              maxLength={6}
              value={captchaCode}
              onChangeText={setCaptchaCode}
              onBlur={() => setTouched((t) => ({ ...t, captcha: true }))}
            />
            <Pressable style={styles.captchaBox} onPress={loadCaptcha} disabled={captchaLoading}>
              {captchaImg && !captchaLoading
                ? <Image source={{ uri: captchaImg }} style={styles.captchaImg} />
                : <Text style={styles.captchaHint}>{captchaLoading ? '加载中…' : captchaFailed ? '点击重试' : '获取验证码'}</Text>}
            </Pressable>
          </View>
        )}
        {!!captchaError && <Text style={styles.err}>{captchaError}</Text>}
        {!captchaError && captchaFailed && <Text style={styles.err}>验证码服务暂时不可用，点击右侧重试</Text>}

        <View style={styles.opts}>
          <Pressable style={styles.chk} onPress={() => setRemember((v) => !v)}>
            <View style={[styles.box, remember && styles.boxOn]}>{remember && <Text style={styles.tick}>✓</Text>}</View>
            <Text style={styles.chkText}>记住账号</Text>
          </Pressable>
          {mode === 'register' ? (
            <Pressable style={styles.chk} onPress={() => setAgreed((v) => !v)}>
              <View style={[styles.box, agreed && styles.boxOn]}>{agreed && <Text style={styles.tick}>✓</Text>}</View>
              <Text style={styles.chkText}>同意<Text style={styles.link}>《隐私政策》</Text></Text>
            </Pressable>
          ) : <Text style={styles.muted}>忘记密码请联系管理员</Text>}
        </View>

        {!!serverError && <View style={styles.serverError}><Text style={styles.serverErrorText}>{serverError}</Text></View>}

        <Pressable style={[styles.button, !canSubmit && styles.buttonDisabled]} onPress={onSubmit} disabled={!canSubmit}>
          {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>{mode === 'login' ? '登 录' : '注册并登录'}</Text>}
        </Pressable>

        <Text style={styles.hint} onPress={() => setMode(mode === 'login' ? 'register' : 'login')}>
          {mode === 'login' ? '还没有账号？立即注册' : '已有账号？去登录'}
        </Text>
        <Text style={styles.foot}>课题阶段免费 · 不代写、不改写 · 结果仅供参考</Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 32, paddingVertical: 48, backgroundColor: '#fff' },
  logo: { width: 56, height: 56, borderRadius: 14, alignSelf: 'center', marginBottom: 12 },
  title: { fontSize: 28, fontWeight: '700', textAlign: 'center', color: '#0D9488' },
  subtitle: { fontSize: 13, textAlign: 'center', color: '#6b7280', marginTop: 8, marginBottom: 28 },
  seg: { flexDirection: 'row', backgroundColor: '#f3f4f6', borderRadius: 10, padding: 3, marginBottom: 18 },
  segBtn: { flex: 1, alignItems: 'center', paddingVertical: 8, borderRadius: 8 },
  segActive: { backgroundColor: '#fff', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 3, elevation: 1 },
  segText: { color: '#6b7280', fontSize: 15 },
  segTextActive: { color: '#111827', fontSize: 15, fontWeight: '600' },
  input: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, marginBottom: 12 },
  inputError: { borderColor: '#ef4444' },
  pwdRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#d1d5db', borderRadius: 10, paddingRight: 12, marginBottom: 12 },
  pwdInput: { flex: 1, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16 },
  eye: { color: '#0D9488', fontSize: 13 },
  err: { color: '#ef4444', fontSize: 12, marginTop: -6, marginBottom: 10, marginLeft: 4 },
  strength: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: -4, marginBottom: 10 },
  bar: { width: 36, height: 4, borderRadius: 2, backgroundColor: '#e5e7eb' },
  strengthText: { fontSize: 12, color: '#6b7280', marginLeft: 6 },
  captchaRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  captchaInput: { flex: 1 },
  captchaBox: { width: 108, height: 46, borderRadius: 10, borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  captchaImg: { width: '100%', height: '100%' },
  captchaHint: { fontSize: 12, color: '#0D9488' },
  opts: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 2, flexWrap: 'wrap', gap: 8 },
  chk: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  box: { width: 18, height: 18, borderRadius: 4, borderWidth: 1.5, borderColor: '#9ca3af', alignItems: 'center', justifyContent: 'center' },
  boxOn: { backgroundColor: '#0D9488', borderColor: '#0D9488' },
  tick: { color: '#fff', fontSize: 12, lineHeight: 14 },
  chkText: { fontSize: 13, color: '#6b7280' },
  link: { color: '#0D9488' },
  muted: { fontSize: 12, color: '#9ca3af' },
  serverError: { marginTop: 12, padding: 10, borderRadius: 10, backgroundColor: 'rgba(239,68,68,0.08)' },
  serverErrorText: { color: '#b91c1c', fontSize: 13, lineHeight: 18 },
  button: { backgroundColor: '#0D9488', borderRadius: 10, paddingVertical: 14, alignItems: 'center', marginTop: 16 },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  hint: { fontSize: 13, color: '#0D9488', textAlign: 'center', marginTop: 20 },
  foot: { fontSize: 11, color: '#9ca3af', textAlign: 'center', marginTop: 10 },
});

// mobile-uniapp/pages/login/login.vue
<script setup>
import { ref, computed, watch } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { useAuth } from '@/store/auth'
import { http, MOCK_MODE } from '@/utils/request'

/*
 * 登录 / 注册页
 *   行内校验 · 密码可见切换 · 注册时密码强度与隐私协议勾选 · 记住账号 · 验证码点击刷新
 *   服务端错误（锁定 / 验证码 / 账号停用）显示在表单内；登录后回到来源页（pending_login_redirect）
 */
const auth = useAuth()
const REMEMBER_KEY = 'remember_username'

const mode = ref('login')   // 'login' | 'register'
const username = ref('')
const password = ref('')
const confirmPassword = ref('')
const showPwd = ref(false)
const remember = ref(true)
const agreed = ref(false)
const captchaId = ref('')
const captchaCode = ref('')
const captchaImg = ref('')
const captchaLoading = ref(false)
const captchaFailed = ref(false)
const serverError = ref('')
const touched = ref({})

const USERNAME_RE = /^[A-Za-z0-9_.@-]{2,64}$/
const usernameError = computed(() => {
  if (!touched.value.username) return ''
  if (!username.value.trim()) return '请输入账号'
  if (mode.value === 'register' && !USERNAME_RE.test(username.value.trim())) return '只能包含字母、数字、_ . @ -，2-64 位'
  return ''
})
const passwordError = computed(() => {
  if (!touched.value.password) return ''
  if (!password.value) return '请输入密码'
  if (mode.value === 'register') {
    if (password.value.length < 6 || password.value.length > 32) return '密码长度 6-32 位'
    if (!/[A-Za-z]/.test(password.value) || !/[0-9]/.test(password.value)) return '需同时包含字母和数字'
    if (password.value.toLowerCase() === username.value.trim().toLowerCase()) return '密码不能与账号相同'
  }
  return ''
})
const confirmError = computed(() => {
  if (mode.value !== 'register' || !touched.value.confirm) return ''
  if (!confirmPassword.value) return '请再次输入密码'
  if (confirmPassword.value !== password.value) return '两次输入的密码不一致'
  return ''
})
const captchaError = computed(() => (touched.value.captcha && captchaImg.value && !captchaCode.value.trim() ? '请输入验证码' : ''))

const strength = computed(() => {
  const p = password.value
  if (!p) return 0
  let s = 0
  if (p.length >= 8) s++
  if (p.length >= 12) s++
  if (/[A-Za-z]/.test(p) && /[0-9]/.test(p)) s++
  if (/[^A-Za-z0-9]/.test(p)) s++
  return Math.min(4, s)
})
const STRENGTH_LABEL = ['', '弱', '一般', '较强', '强']

const canSubmit = computed(() => {
  if (auth.loading) return false
  if (!username.value.trim() || !password.value) return false
  if (captchaImg.value && !captchaCode.value.trim()) return false
  if (mode.value === 'register') {
    if (!confirmPassword.value || confirmPassword.value !== password.value) return false
    if (!agreed.value) return false
  }
  return true
})

async function loadCaptcha() {
  if (MOCK_MODE) { captchaId.value = ''; captchaImg.value = ''; return }
  captchaLoading.value = true
  captchaFailed.value = false
  try {
    const data = await http({ url: '/api/v1/auth/captcha', method: 'GET', auth: false, silent: true })
    captchaId.value = data.captchaId
    captchaImg.value = data.imageBase64
  } catch (e) {
    captchaId.value = ''
    captchaImg.value = ''
    captchaFailed.value = true
  } finally {
    captchaLoading.value = false
    captchaCode.value = ''
  }
}

onLoad((q) => {
  if (q && q.mode === 'register') mode.value = 'register'
  const saved = uni.getStorageSync(REMEMBER_KEY)
  if (saved) { username.value = saved; remember.value = true }
  loadCaptcha()
})

watch(mode, () => {
  serverError.value = ''
  touched.value = {}
  confirmPassword.value = ''
  if (!captchaImg.value) loadCaptcha()
})

function afterLogin() {
  if (remember.value) uni.setStorageSync(REMEMBER_KEY, username.value.trim())
  else uni.removeStorageSync(REMEMBER_KEY)
  const back = uni.getStorageSync('pending_login_redirect')
  uni.removeStorageSync('pending_login_redirect')
  if (back && /^\/pages\//.test(back) && !back.startsWith('/pages/login/')) {
    uni.reLaunch({ url: back })
  } else {
    uni.reLaunch({ url: '/pages/home/home' })
  }
}

async function onSubmit() {
  touched.value = { username: true, password: true, confirm: true, captcha: true }
  serverError.value = ''
  if (usernameError.value || passwordError.value || confirmError.value || captchaError.value) return
  if (mode.value === 'register' && !agreed.value) {
    serverError.value = '请先阅读并同意《隐私政策》'
    return
  }
  const u = username.value.trim()
  try {
    if (mode.value === 'register') {
      await auth.register(u, password.value, confirmPassword.value, captchaId.value, captchaCode.value)
      uni.showToast({ title: '注册成功', icon: 'success' })
    } else {
      await auth.login(u, password.value, captchaId.value, captchaCode.value)
    }
    afterLogin()
  } catch (e) {
    serverError.value = e?.message || (mode.value === 'register' ? '注册失败' : '登录失败')
    loadCaptcha()   // 验证码一次性，失败后必须换一张
  }
}

function goPrivacy() { uni.navigateTo({ url: '/pages/about/privacy' }) }

/**
 * 微信一键登录（Wave 3.1）
 * 流程：wx.login → code → POST /api/v1/auth/wechat/login
 */
async function onWechatLogin() {
  uni.login({
    provider: 'weixin',
    success: async (res) => {
      if (!res.code) {
        uni.showToast({ title: '未拿到微信 code', icon: 'none' })
        return
      }
      try {
        await auth.loginByWechat({ code: res.code })
        afterLogin()
      } catch (e) {
        serverError.value = e?.message || '微信登录失败'
      }
    },
    fail: () => uni.showToast({ title: '微信授权失败', icon: 'none' }),
  })
}
</script>

<template>
  <view class="page">
    <view class="hero">
      <image class="logo" src="/static/logo.png" mode="aspectFill" />
      <text class="brand">知源</text>
      <text class="tagline">看得懂的论文 AI 率检测 · 溯源 · 不代写</text>
    </view>

    <view class="form">
      <view class="seg">
        <text class="seg-item" :class="{ active: mode === 'login' }" @click="mode = 'login'">登录</text>
        <text class="seg-item" :class="{ active: mode === 'register' }" @click="mode = 'register'">注册</text>
      </view>

      <view class="field" :class="{ error: usernameError }">
        <input v-model="username" class="input" placeholder="学号 / 工号 / 邮箱" placeholder-style="color: rgba(60,60,67,0.30)" :cursor-spacing="24" :adjust-position="true" @blur="touched.username = true" />
      </view>
      <text v-if="usernameError" class="err">{{ usernameError }}</text>

      <view class="field pwd" :class="{ error: passwordError }">
        <input v-model="password" class="input" :placeholder="mode === 'register' ? '设置密码（6-32 位，含字母和数字）' : '密码'" :password="!showPwd" placeholder-style="color: rgba(60,60,67,0.30)" :cursor-spacing="24" :adjust-position="true" @blur="touched.password = true" />
        <text class="eye" @click="showPwd = !showPwd">{{ showPwd ? '隐藏' : '显示' }}</text>
      </view>
      <text v-if="passwordError" class="err">{{ passwordError }}</text>
      <view v-if="mode === 'register' && password" class="strength">
        <view v-for="n in 4" :key="n" class="bar" :class="{ on: n <= strength, ['lv' + strength]: n <= strength }" />
        <text class="strength-text">{{ STRENGTH_LABEL[strength] }}</text>
      </view>

      <template v-if="mode === 'register'">
        <view class="field" :class="{ error: confirmError }">
          <input v-model="confirmPassword" class="input" placeholder="再次输入密码" :password="!showPwd" placeholder-style="color: rgba(60,60,67,0.30)" :cursor-spacing="24" :adjust-position="true" @blur="touched.confirm = true" />
        </view>
        <text v-if="confirmError" class="err">{{ confirmError }}</text>
      </template>

      <view v-if="!MOCK_MODE" class="captcha-row">
        <view class="field captcha-field" :class="{ error: captchaError }">
          <input v-model="captchaCode" class="input" placeholder="验证码" maxlength="6" placeholder-style="color: rgba(60,60,67,0.30)" :cursor-spacing="24" :adjust-position="true" @blur="touched.captcha = true" />
        </view>
        <view class="captcha-box" hover-class="captcha-box-hover" @click="loadCaptcha">
          <image v-if="captchaImg && !captchaLoading" class="captcha-img" :src="captchaImg" mode="aspectFill" />
          <text v-else class="captcha-hint">{{ captchaLoading ? '加载中…' : captchaFailed ? '点击重试' : '获取验证码' }}</text>
        </view>
      </view>
      <text v-if="captchaError" class="err">{{ captchaError }}</text>
      <text v-else-if="captchaFailed" class="err">验证码服务暂时不可用，点击右侧重试</text>

      <view class="opts">
        <view class="chk" @click="remember = !remember">
          <view class="box" :class="{ on: remember }"><text v-if="remember">✓</text></view>
          <text class="chk-text">记住账号</text>
        </view>
        <view v-if="mode === 'register'" class="chk" @click="agreed = !agreed">
          <view class="box" :class="{ on: agreed }"><text v-if="agreed">✓</text></view>
          <text class="chk-text">同意</text><text class="link" @click.stop="goPrivacy">《隐私政策》</text>
        </view>
        <text v-else class="muted">忘记密码请联系管理员</text>
      </view>

      <view v-if="serverError" class="server-error"><text>{{ serverError }}</text></view>

      <button class="submit" :class="{ disabled: !canSubmit }" :disabled="!canSubmit" :loading="auth.loading" @click="onSubmit">{{ mode === 'login' ? '登 录' : '注册并登录' }}</button>

      <!-- 微信一键登录 · 仅小程序端可见（H5 不支持 uni.login provider=weixin）-->
      <!-- #ifdef MP-WEIXIN -->
      <view class="divider"><text class="divider-text">或</text></view>
      <button class="wechat-btn" @click="onWechatLogin">
        <view class="wechat-icon" />
        <text class="wechat-text">微信一键登录</text>
      </button>
      <!-- #endif -->

      <text class="footer-hint">{{ mode === 'login' ? '还没有账号？' : '已有账号？' }}<text class="switch-link" @click="mode = mode === 'login' ? 'register' : 'login'">{{ mode === 'login' ? '立即注册' : '去登录' }}</text></text>
      <text class="foot-note">课题阶段免费 · 不代写、不改写 · 结果仅供参考</text>
    </view>
  </view>
</template>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: $bg-primary;
  padding: #{"calc(140rpx + env(safe-area-inset-top))"} $sp-8 60rpx;
}

/* Hero */
.hero { margin-bottom: 72rpx; }
.logo { width: 96rpx; height: 96rpx; border-radius: 24rpx; margin-bottom: $sp-4; }
.brand {
  display: block;
  font-size: $fs-large-title;
  font-weight: $fw-bold;
  letter-spacing: $tracking-tight;
  color: $label-primary;
  line-height: $lh-tight;
}
.tagline { display: block; font-size: $fs-subhead; color: $label-secondary; margin-top: $sp-2; }

/* 分段 */
.seg { display: flex; background: $bg-grouped-primary; border-radius: $radius-card; padding: 4rpx; margin-bottom: $sp-4; }
.seg-item {
  flex: 1; text-align: center; padding: 12rpx 0;
  font-size: $fs-subhead; color: $label-secondary; border-radius: 12rpx;
  &.active { background: $bg-primary; color: $label-primary; font-weight: $fw-semibold; box-shadow: $shadow-card; }
}

/* 输入框 */
.field {
  background: $bg-grouped-primary;
  border-radius: $radius-card;
  padding: 4rpx $sp-4;
  margin-bottom: $sp-3;
  border: $stroke-hairline solid transparent;
  &.error { border-color: $danger-solid; }
  &.pwd { display: flex; align-items: center; }
}
.input { flex: 1; height: $size-input-h; font-size: $fs-body; color: $label-primary; min-width: 0; }
.eye { flex: none; font-size: $fs-footnote; color: $brand-primary; padding-left: $sp-2; }
.err { display: block; margin: -8rpx 0 $sp-3 $sp-2; font-size: $fs-caption-1; color: $danger-fg; }

.strength { display: flex; align-items: center; gap: 8rpx; margin: -4rpx 0 $sp-3 $sp-1; }
.bar { width: 64rpx; height: 8rpx; border-radius: 4rpx; background: $fill-tertiary; }
.bar.on.lv1 { background: $danger-solid; } .bar.on.lv2 { background: $warning-solid; } .bar.on.lv3 { background: $info-fg; } .bar.on.lv4 { background: $success-solid; }
.strength-text { font-size: $fs-caption-1; color: $label-secondary; margin-left: $sp-2; }

.captcha-row { display: flex; align-items: flex-start; gap: $sp-2; }
.captcha-field { flex: 1; }
.captcha-box {
  flex: none; width: 200rpx; height: $size-input-h;
  border-radius: $radius-card; border: $stroke-hairline solid $separator;
  display: flex; align-items: center; justify-content: center; overflow: hidden;
  background: $bg-primary;
}
.captcha-box-hover { opacity: 0.7; }
.captcha-img { width: 100%; height: 100%; }
.captcha-hint { font-size: $fs-caption-1; color: $brand-primary; }

.opts { display: flex; justify-content: space-between; align-items: center; margin: $sp-1 $sp-1 0; flex-wrap: wrap; gap: $sp-2; }
.chk { display: flex; align-items: center; gap: 10rpx; }
.box {
  width: 34rpx; height: 34rpx; border-radius: 8rpx; border: 2rpx solid $label-tertiary;
  display: flex; align-items: center; justify-content: center;
  &.on { background: $brand-primary; border-color: $brand-primary; }
  text { color: #fff; font-size: 22rpx; line-height: 1; }
}
.chk-text { font-size: $fs-footnote; color: $label-secondary; }
.link { font-size: $fs-footnote; color: $brand-primary; }
.muted { font-size: $fs-caption-1; color: $label-tertiary; }

.server-error {
  margin-top: $sp-3; padding: $sp-2 $sp-3; border-radius: $radius-md;
  background: $danger-bg;
  text { font-size: $fs-footnote; color: $danger-fg; line-height: $lh-normal; }
}

/* 主按钮 */
.submit {
  margin-top: $sp-5;
  height: $size-btn-h-lg;
  line-height: $size-btn-h-lg;
  background: $brand-primary;
  color: #FFFFFF;
  font-size: $fs-headline;
  font-weight: $fw-semibold;
  border-radius: $radius-pill;
  letter-spacing: 2rpx;
  transition: transform $duration-fast $ease-standard, opacity $duration-fast;
  &:active { transform: scale(#{$tap-scale}); opacity: 0.88; }
  &.disabled { opacity: 0.45; }
}

.divider {
  display: flex; align-items: center; justify-content: center;
  margin: $sp-5 0 $sp-3;
  &::before, &::after { content: ''; flex: 1; height: $stroke-hairline; background: $separator; }
}
.divider-text { padding: 0 $sp-3; font-size: $fs-caption-1; color: $label-secondary; }

.wechat-btn {
  height: $size-btn-h-lg; line-height: $size-btn-h-lg;
  background: #07C160; color: #FFFFFF;
  font-size: $fs-headline; font-weight: $fw-semibold; border-radius: $radius-pill;
  display: flex; align-items: center; justify-content: center; gap: $sp-2;
  transition: transform $duration-fast $ease-standard, opacity $duration-fast;
  &:active { transform: scale(#{$tap-scale}); opacity: 0.88; }
}
.wechat-icon {
  width: 40rpx; height: 40rpx;
  background: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23FFFFFF'><path d='M9.5 4C5.4 4 2 6.6 2 10c0 1.8 1 3.5 2.6 4.6L4 17l2.7-1.4c.9.2 1.8.3 2.8.3.3 0 .6 0 .9-.1-.2-.6-.4-1.3-.4-2 0-3.3 3.3-6 7.5-6 .3 0 .6 0 .9.1C17.7 5.6 13.9 4 9.5 4zm-3 3.6c.6 0 1 .4 1 1s-.4 1-1 1-1-.4-1-1 .4-1 1-1zm5.5 0c.6 0 1 .4 1 1s-.4 1-1 1-1-.4-1-1 .4-1 1-1z'/><path d='M22 14c0-2.8-2.9-5-6.5-5S9 11.2 9 14s2.9 5 6.5 5c.8 0 1.6-.1 2.3-.3l2 1-.5-2C21 16.7 22 15.4 22 14zm-9-1.4c.4 0 .8.3.8.8 0 .4-.3.8-.8.8-.4 0-.8-.3-.8-.8 0-.4.4-.8.8-.8zm4.5 0c.4 0 .8.3.8.8 0 .4-.3.8-.8.8-.4 0-.8-.3-.8-.8 0-.4.3-.8.8-.8z'/></svg>") no-repeat center / contain;
}

.footer-hint { display: block; margin-top: $sp-6; font-size: $fs-caption-1; color: $label-secondary; text-align: center; line-height: $lh-normal; }
.switch-link { color: $brand-primary; }
.foot-note { display: block; margin-top: $sp-3; font-size: $fs-caption-2; color: $label-tertiary; text-align: center; }
</style>
